import type {
  MarketConsensusHoldingCardModel,
  MarketConsensusPortfolioSummaryModel,
} from "@/lib/client/marketConsensus/types";
import {
  MARKET_CONSENSUS_CRYPTO_DISCLAIMER,
  MARKET_CONSENSUS_UNAVAILABLE_COPY,
  MARKET_CONSENSUS_UNAVAILABLE_TITLE,
} from "@/lib/client/marketConsensus/types";

export function buildMarketConsensusDemoSummary(): MarketConsensusPortfolioSummaryModel {
  return {
    summary:
      "Illustrative portfolio-level consensus snapshot for interface preview. Figures are not based on live analyst data.",
    holdingsWithCoverage: 4,
    positiveConsensus: 2,
    mixedConsensus: 1,
    limitedCoverage: 3,
    isDemoData: true,
  };
}

/** Synthetic cards illustrating every supported UI state — development only. */
export function buildMarketConsensusDemoPreviewCards(): MarketConsensusHoldingCardModel[] {
  return [
    {
      id: "demo-equity",
      state: "equity_coverage",
      symbol: "DEMO",
      name: "Demo Equity Holding",
      weightPercent: 12.4,
      currentValueLabel: "€4,820",
      coverageType: "Analyst coverage",
      statusLabel: "Positive consensus",
      analystAgreementLabel: "Moderate agreement",
      ratingDistribution: { buy: 14, hold: 6, sell: 2 },
      priceTargetLabel: "Third-party price targets: €52 – €61",
      impliedUpsideLabel: "Consensus-implied upside: +8.2% (Demo)",
      summary:
        "Demo summary: available third-party views skew constructive, with debate around near-term margins. (Demo data)",
      supportingFactors: [
        "Demo factor: recurring revenue visibility",
        "Demo factor: balance sheet flexibility",
      ],
      keyRisks: [
        "Demo risk: demand normalization",
        "Demo risk: input cost volatility",
      ],
      sourceLabel: "Demo provider aggregate",
      updatedAtLabel: "24 Jul 2026 (Demo)",
      isDemoData: true,
    },
    {
      id: "demo-etf",
      state: "etf_outlook",
      symbol: "DEMO-ETF",
      name: "Demo Global Equity ETF",
      weightPercent: 28.1,
      currentValueLabel: "€10,940",
      coverageType: "Underlying market outlook",
      statusLabel: "Underlying market outlook",
      analystAgreementLabel: "Broad index-level view",
      ratingDistribution: null,
      priceTargetLabel: null,
      impliedUpsideLabel: null,
      summary:
        "Demo summary: third-party research focuses on the underlying equity market rather than a single ETF rating. (Demo data)",
      supportingFactors: [
        "Demo factor: diversified regional exposure",
        "Demo factor: earnings breadth across sectors",
      ],
      keyRisks: [
        "Demo risk: regional growth divergence",
        "Demo risk: currency effects on returns",
      ],
      sourceLabel: "Demo market research aggregate",
      updatedAtLabel: "24 Jul 2026 (Demo)",
      isDemoData: true,
    },
    {
      id: "demo-crypto",
      state: "crypto_outlook",
      symbol: "DEMO-BTC",
      name: "Demo Bitcoin-linked ETP",
      weightPercent: 5.2,
      currentValueLabel: "€2,030",
      coverageType: "Market outlook",
      statusLabel: "Market outlook",
      analystAgreementLabel: "Wide forecast dispersion",
      ratingDistribution: null,
      priceTargetLabel: null,
      impliedUpsideLabel: null,
      summary:
        "Demo summary: third-party crypto outlooks vary widely and are less standardized than equity targets. (Demo data)",
      supportingFactors: ["Demo factor: institutional adoption trends"],
      keyRisks: ["Demo risk: regulatory developments", "Demo risk: liquidity conditions"],
      sourceLabel: "Demo market outlook sources",
      updatedAtLabel: "24 Jul 2026 (Demo)",
      cryptoDisclaimer: MARKET_CONSENSUS_CRYPTO_DISCLAIMER,
      isDemoData: true,
    },
    {
      id: "demo-unavailable",
      state: "no_coverage",
      symbol: "DEMO-NA",
      name: "Demo Unclassified Holding",
      weightPercent: 3.8,
      currentValueLabel: "€1,480",
      coverageType: "No reliable coverage",
      statusLabel: "Limited coverage",
      analystAgreementLabel: null,
      ratingDistribution: null,
      priceTargetLabel: null,
      impliedUpsideLabel: null,
      summary: MARKET_CONSENSUS_UNAVAILABLE_COPY,
      supportingFactors: [],
      keyRisks: [],
      sourceLabel: null,
      updatedAtLabel: null,
      unavailableTitle: MARKET_CONSENSUS_UNAVAILABLE_TITLE,
      unavailableCopy: MARKET_CONSENSUS_UNAVAILABLE_COPY,
      isDemoData: true,
    },
    {
      id: "demo-loading",
      state: "loading",
      symbol: "DEMO",
      name: "Loading preview",
      weightPercent: null,
      currentValueLabel: null,
      coverageType: "Analyst coverage",
      statusLabel: null,
      analystAgreementLabel: null,
      ratingDistribution: null,
      priceTargetLabel: null,
      impliedUpsideLabel: null,
      summary: "",
      supportingFactors: [],
      keyRisks: [],
      sourceLabel: null,
      updatedAtLabel: null,
      isDemoData: true,
    },
    {
      id: "demo-error",
      state: "error",
      symbol: "DEMO-ERR",
      name: "Demo Error Holding",
      weightPercent: 6.1,
      currentValueLabel: "€2,380",
      coverageType: "Analyst coverage",
      statusLabel: null,
      analystAgreementLabel: null,
      ratingDistribution: null,
      priceTargetLabel: null,
      impliedUpsideLabel: null,
      summary: MARKET_CONSENSUS_UNAVAILABLE_COPY,
      supportingFactors: [],
      keyRisks: [],
      sourceLabel: null,
      updatedAtLabel: null,
      errorMessage:
        "Demo state: consensus data could not be loaded for this holding. Try again after the data connection is enabled.",
      isDemoData: true,
    },
  ];
}
