import { ANALYSIS_EXPLORE_DESTINATIONS } from "@/lib/services/analysisGlance";

export const ANALYSIS_EXPLORE_MOBILE_COMPACT_TITLES = [
  "Allocation",
  "Performance",
  "Scenarios",
  "Goals",
  "What matters?",
  "Reports",
] as const;

export const ANALYSIS_EXPLORE_ITEM_HREFS = [
  ANALYSIS_EXPLORE_DESTINATIONS.allocation,
  ANALYSIS_EXPLORE_DESTINATIONS.exposure,
  ANALYSIS_EXPLORE_DESTINATIONS.concentration,
  ANALYSIS_EXPLORE_DESTINATIONS.xray,
  ANALYSIS_EXPLORE_DESTINATIONS.performance,
  ANALYSIS_EXPLORE_DESTINATIONS.attribution,
  ANALYSIS_EXPLORE_DESTINATIONS.history,
  ANALYSIS_EXPLORE_DESTINATIONS.crypto,
  ANALYSIS_EXPLORE_DESTINATIONS.bonds,
  ANALYSIS_EXPLORE_DESTINATIONS.cash,
  ANALYSIS_EXPLORE_DESTINATIONS.dividends,
  ANALYSIS_EXPLORE_DESTINATIONS.consensus,
  ANALYSIS_EXPLORE_DESTINATIONS.scenarios,
  ANALYSIS_EXPLORE_DESTINATIONS.scorecard,
  ANALYSIS_EXPLORE_DESTINATIONS.goals,
  ANALYSIS_EXPLORE_DESTINATIONS.whatIf,
  ANALYSIS_EXPLORE_DESTINATIONS.whatHappened,
  ANALYSIS_EXPLORE_DESTINATIONS.whatMatters,
  ANALYSIS_EXPLORE_DESTINATIONS.onTrack,
  ANALYSIS_EXPLORE_DESTINATIONS.whatsAhead,
  ANALYSIS_EXPLORE_DESTINATIONS.reports,
  ANALYSIS_EXPLORE_DESTINATIONS.methodology,
] as const;
